services:

  payum.payrexx_checkout_gateway_factory:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments: [Wvision\Payum\Payrexx\PayumPayrexxCheckoutGatewayFactory]
    tags:
      - { name: payum.gateway_factory_builder, factory: payrexx_checkout }

  CoreShop\Payum\PayrexxCheckoutBundle\Action\PrepareTransactionAction:
    public: true
    tags:
      - {
        name: payum.action,
        factory: payrexx_checkout,
        alias: coreshop.payrexx_checkout.prepare_transaction
      }

  CoreShop\Payum\PayrexxCheckoutBundle\Form\Type\PayrexxCheckoutType:
    tags:
      - { name: coreshop.gateway_configuration_type, type: payrexx_checkout }
      - { name: form.type }
